/* The following code was generated by JFlex 1.4.3 on 12/14/11 4:41 PM */

package com.eightbitmage.moonscript.lang.lexer;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import java.util.*;
import java.lang.reflect.Field;
import org.jetbrains.annotations.NotNull;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 12/14/11 4:41 PM from the specification file
 * <tt>C:/Dev/IdeaProjects/moonscript-idea/src/com/eightbitmage/moonscript/lang/lexer/moon.flex</tt>
 */
class _MoonLexer implements FlexLexer, MoonTokenTypes {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int XLONGSTRING = 2;
  public static final int XSTRINGA = 12;
  public static final int XLONGCOMMENT = 8;
  public static final int XSHORTCOMMENT = 6;
  public static final int YYINITIAL = 0;
  public static final int XSTRINGQ = 10;
  public static final int XLONGSTRING_BEGIN = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6, 6
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\3\2\0\1\2\22\0\1\1\1\47\1\44\1\46"+
    "\1\0\1\53\1\0\1\45\1\55\1\56\1\52\1\10\1\62\1\16"+
    "\1\14\1\54\1\11\11\6\1\64\1\63\1\50\1\15\1\36\2\0"+
    "\4\13\1\7\1\13\21\5\1\12\2\5\1\4\1\66\1\57\1\65"+
    "\1\5\1\0\1\17\1\22\1\34\1\21\1\24\1\32\1\5\1\40"+
    "\1\31\1\5\1\25\1\27\1\43\1\20\1\26\1\37\1\5\1\23"+
    "\1\30\1\35\1\33\1\5\1\41\1\42\2\5\1\60\1\0\1\61"+
    "\1\51\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\7\0\1\1\1\2\2\3\1\4\1\5\1\6\1\7"+
    "\1\6\1\10\1\11\1\12\15\5\1\13\1\5\1\14"+
    "\1\15\1\16\1\1\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\3\34\1\35\2\36\1\37\2\40\3\41\1\42\2\43"+
    "\1\44\1\42\2\45\1\44\1\42\1\46\2\0\1\6"+
    "\1\7\1\0\1\6\1\47\1\50\1\12\1\51\1\52"+
    "\3\5\1\53\5\5\1\54\1\5\1\55\1\56\10\5"+
    "\1\57\1\5\1\60\1\61\1\62\1\20\1\21\1\22"+
    "\1\0\1\63\1\0\1\64\1\0\2\6\1\65\1\47"+
    "\1\0\1\51\1\66\1\67\1\70\3\5\1\71\5\5"+
    "\1\72\6\5\1\73\1\0\2\74\3\5\1\75\7\5"+
    "\1\76\1\77\1\5\2\0\1\100\4\5\1\101\1\5"+
    "\1\102\1\5\1\103\1\104\1\105\1\0\1\106\1\107"+
    "\1\110\1\111\1\112\1\5\1\0\1\5\1\52";

  private static int [] zzUnpackAction() {
    int [] result = new int[185];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\156\0\245\0\334\0\u0113\0\u014a\0\u0181"+
    "\0\u01b8\0\u01ef\0\u0181\0\u0226\0\u025d\0\u0294\0\u02cb\0\u0302"+
    "\0\u0339\0\u0370\0\u03a7\0\u03de\0\u0415\0\u044c\0\u0483\0\u04ba"+
    "\0\u04f1\0\u0528\0\u055f\0\u0596\0\u05cd\0\u0604\0\u063b\0\u0672"+
    "\0\u06a9\0\u06e0\0\u0181\0\u0181\0\u0717\0\u074e\0\u0785\0\u07bc"+
    "\0\u07f3\0\u082a\0\u0181\0\u0181\0\u0181\0\u0181\0\u0181\0\u0181"+
    "\0\u0181\0\u0181\0\u0181\0\u0181\0\u0861\0\u0898\0\u0181\0\u08cf"+
    "\0\u0181\0\u0181\0\u0906\0\u0181\0\u0181\0\u093d\0\u0974\0\u0181"+
    "\0\u09ab\0\u0181\0\u09e2\0\u0a19\0\u0a50\0\u0181\0\u0a87\0\u0abe"+
    "\0\u0181\0\u0226\0\u0af5\0\u0b2c\0\u0181\0\u0b63\0\u0b9a\0\u0bd1"+
    "\0\u0181\0\u0181\0\u0c08\0\u0181\0\u0c3f\0\u0c76\0\u0cad\0\u025d"+
    "\0\u0ce4\0\u0d1b\0\u0d52\0\u0d89\0\u0dc0\0\u025d\0\u0df7\0\u025d"+
    "\0\u025d\0\u0e2e\0\u0e65\0\u0e9c\0\u0ed3\0\u0f0a\0\u0f41\0\u0f78"+
    "\0\u0faf\0\u0181\0\u0fe6\0\u0181\0\u0181\0\u0181\0\u0181\0\u0181"+
    "\0\u0181\0\u0898\0\u0181\0\u0974\0\u0181\0\u0b9a\0\u101d\0\u0b63"+
    "\0\u0181\0\u0181\0\u1054\0\u108b\0\u025d\0\u025d\0\u025d\0\u10c2"+
    "\0\u10f9\0\u1130\0\u025d\0\u1167\0\u119e\0\u11d5\0\u120c\0\u1243"+
    "\0\u025d\0\u127a\0\u12b1\0\u12e8\0\u131f\0\u1356\0\u138d\0\u0181"+
    "\0\u13c4\0\u13fb\0\u1432\0\u1469\0\u14a0\0\u14d7\0\u150e\0\u1545"+
    "\0\u157c\0\u15b3\0\u15ea\0\u1621\0\u1658\0\u168f\0\u025d\0\u025d"+
    "\0\u16c6\0\u1432\0\u16fd\0\u025d\0\u1734\0\u176b\0\u17a2\0\u17d9"+
    "\0\u025d\0\u1810\0\u025d\0\u1847\0\u025d\0\u025d\0\u025d\0\u187e"+
    "\0\u025d\0\u025d\0\u025d\0\u025d\0\u025d\0\u18b5\0\u18ec\0\u1923"+
    "\0\u025d";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[185];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\15"+
    "\1\17\1\20\2\15\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\15\1\32\1\33\1\15"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\2\15\1\42"+
    "\2\15\1\43\1\44\1\45\1\46\1\47\1\46\1\50"+
    "\1\51\1\52\1\53\1\54\1\55\1\56\1\57\1\60"+
    "\1\61\1\62\1\63\1\10\2\64\1\65\54\64\1\66"+
    "\7\64\2\67\1\70\1\71\63\67\2\72\1\73\1\74"+
    "\63\72\2\75\1\76\54\75\1\77\7\75\2\100\1\101"+
    "\1\102\40\100\1\103\21\100\1\104\2\100\1\105\1\106"+
    "\41\100\1\107\20\100\1\110\70\0\1\11\70\0\1\13"+
    "\67\0\1\111\10\0\1\112\56\0\3\15\1\0\3\15"+
    "\3\0\17\15\1\0\5\15\31\0\1\16\1\113\1\0"+
    "\1\16\2\0\1\114\7\0\1\113\57\0\1\115\57\0"+
    "\1\16\1\113\1\0\1\16\1\116\1\0\1\114\7\0"+
    "\1\113\15\0\1\116\32\0\1\117\2\0\1\117\2\0"+
    "\1\120\67\0\1\121\66\0\1\122\1\123\17\0\1\124"+
    "\35\0\3\15\1\0\3\15\3\0\1\15\1\125\15\15"+
    "\1\0\5\15\30\0\3\15\1\0\3\15\3\0\7\15"+
    "\1\126\2\15\1\127\4\15\1\0\5\15\30\0\3\15"+
    "\1\0\3\15\3\0\7\15\1\130\7\15\1\0\5\15"+
    "\30\0\3\15\1\0\3\15\3\0\4\15\1\131\12\15"+
    "\1\0\5\15\30\0\3\15\1\0\3\15\3\0\5\15"+
    "\1\132\11\15\1\0\5\15\30\0\3\15\1\0\3\15"+
    "\3\0\1\15\1\133\6\15\1\134\6\15\1\0\3\15"+
    "\1\135\1\15\30\0\3\15\1\0\3\15\3\0\4\15"+
    "\1\136\12\15\1\0\5\15\30\0\3\15\1\0\3\15"+
    "\3\0\7\15\1\137\7\15\1\0\5\15\30\0\3\15"+
    "\1\0\3\15\3\0\1\15\1\140\11\15\1\141\3\15"+
    "\1\0\4\15\1\142\30\0\3\15\1\0\3\15\3\0"+
    "\1\143\6\15\1\144\4\15\1\145\2\15\1\0\5\15"+
    "\30\0\3\15\1\0\3\15\3\0\1\15\1\146\15\15"+
    "\1\0\5\15\30\0\3\15\1\0\3\15\3\0\10\15"+
    "\1\147\6\15\1\0\5\15\30\0\3\15\1\0\3\15"+
    "\3\0\4\15\1\150\12\15\1\0\1\15\1\151\3\15"+
    "\40\0\1\152\56\0\3\15\1\0\3\15\3\0\17\15"+
    "\1\0\1\15\1\153\3\15\72\0\1\154\34\0\1\155"+
    "\66\0\1\156\66\0\1\157\66\0\1\160\66\0\1\161"+
    "\54\0\1\64\100\0\1\162\41\0\1\163\12\0\1\71"+
    "\66\0\1\74\66\0\1\75\100\0\1\164\41\0\1\165"+
    "\12\0\1\102\127\0\1\100\25\0\2\100\12\0\2\100"+
    "\1\0\2\100\6\0\1\100\2\0\1\100\6\0\2\100"+
    "\11\0\1\100\6\0\1\100\3\0\1\106\130\0\1\100"+
    "\24\0\2\100\12\0\2\100\1\0\2\100\6\0\1\100"+
    "\2\0\1\100\7\0\1\100\11\0\1\100\6\0\1\100"+
    "\6\0\1\117\1\0\1\166\1\117\4\0\1\166\56\0"+
    "\1\167\2\0\1\167\63\0\2\170\1\0\1\170\1\0"+
    "\1\170\3\0\1\170\1\0\2\170\1\0\1\170\5\0"+
    "\1\170\1\0\1\170\40\0\1\117\2\0\1\117\71\0"+
    "\1\171\1\172\55\0\1\173\11\0\1\174\55\0\3\15"+
    "\1\0\3\15\3\0\2\15\1\175\14\15\1\0\5\15"+
    "\30\0\3\15\1\0\3\15\3\0\16\15\1\176\1\0"+
    "\5\15\30\0\3\15\1\0\3\15\3\0\10\15\1\177"+
    "\6\15\1\0\5\15\30\0\3\15\1\0\3\15\3\0"+
    "\5\15\1\200\11\15\1\0\5\15\30\0\3\15\1\0"+
    "\3\15\3\0\16\15\1\201\1\0\1\202\4\15\30\0"+
    "\3\15\1\0\3\15\3\0\2\15\1\203\14\15\1\0"+
    "\5\15\30\0\3\15\1\0\3\15\3\0\11\15\1\204"+
    "\5\15\1\0\5\15\30\0\3\15\1\0\3\15\3\0"+
    "\17\15\1\0\1\205\4\15\30\0\3\15\1\0\3\15"+
    "\3\0\15\15\1\206\1\15\1\0\5\15\30\0\3\15"+
    "\1\0\3\15\3\0\17\15\1\0\1\207\4\15\30\0"+
    "\3\15\1\0\3\15\3\0\10\15\1\210\6\15\1\0"+
    "\5\15\30\0\3\15\1\0\3\15\3\0\4\15\1\211"+
    "\12\15\1\0\5\15\30\0\3\15\1\0\3\15\3\0"+
    "\1\15\1\212\15\15\1\0\5\15\30\0\3\15\1\0"+
    "\3\15\3\0\16\15\1\213\1\0\5\15\30\0\3\15"+
    "\1\0\3\15\3\0\1\214\16\15\1\0\5\15\30\0"+
    "\3\15\1\0\3\15\3\0\14\15\1\215\2\15\1\0"+
    "\5\15\30\0\3\15\1\0\3\15\3\0\5\15\1\216"+
    "\11\15\1\0\5\15\30\0\3\15\1\0\3\15\3\0"+
    "\12\15\1\217\4\15\1\0\5\15\31\0\1\167\1\113"+
    "\1\0\1\167\12\0\1\113\46\0\1\220\10\0\1\173"+
    "\51\0\2\221\1\222\1\223\12\221\1\174\50\221\5\0"+
    "\3\15\1\0\3\15\3\0\1\224\16\15\1\0\5\15"+
    "\30\0\3\15\1\0\3\15\3\0\14\15\1\225\2\15"+
    "\1\0\5\15\30\0\3\15\1\0\3\15\3\0\5\15"+
    "\1\226\11\15\1\0\5\15\30\0\3\15\1\0\3\15"+
    "\3\0\5\15\1\227\11\15\1\0\5\15\30\0\3\15"+
    "\1\0\3\15\3\0\7\15\1\230\7\15\1\0\5\15"+
    "\30\0\3\15\1\0\3\15\3\0\1\231\16\15\1\0"+
    "\5\15\30\0\3\15\1\0\3\15\3\0\7\15\1\232"+
    "\7\15\1\0\5\15\30\0\3\15\1\0\3\15\3\0"+
    "\11\15\1\233\5\15\1\0\5\15\30\0\3\15\1\0"+
    "\3\15\3\0\15\15\1\234\1\15\1\0\5\15\30\0"+
    "\3\15\1\0\3\15\3\0\12\15\1\235\4\15\1\0"+
    "\5\15\30\0\3\15\1\0\3\15\3\0\11\15\1\236"+
    "\5\15\1\0\5\15\30\0\3\15\1\0\3\15\3\0"+
    "\5\15\1\237\11\15\1\0\5\15\30\0\3\15\1\0"+
    "\3\15\3\0\1\15\1\240\15\15\1\0\5\15\30\0"+
    "\3\15\1\0\3\15\3\0\10\15\1\241\6\15\1\0"+
    "\5\15\23\0\2\221\1\222\1\223\63\221\1\0\1\242"+
    "\1\0\1\223\12\0\1\243\51\0\1\242\14\0\1\243"+
    "\55\0\3\15\1\0\3\15\3\0\6\15\1\244\10\15"+
    "\1\0\5\15\30\0\3\15\1\0\3\15\3\0\4\15"+
    "\1\245\12\15\1\0\5\15\30\0\3\15\1\0\3\15"+
    "\3\0\1\246\16\15\1\0\5\15\30\0\3\15\1\0"+
    "\3\15\3\0\12\15\1\247\4\15\1\0\5\15\30\0"+
    "\3\15\1\0\3\15\3\0\4\15\1\250\12\15\1\0"+
    "\5\15\30\0\3\15\1\0\3\15\3\0\10\15\1\251"+
    "\6\15\1\0\5\15\30\0\3\15\1\0\3\15\3\0"+
    "\4\15\1\252\12\15\1\0\5\15\30\0\3\15\1\0"+
    "\3\15\3\0\5\15\1\253\11\15\1\0\5\15\30\0"+
    "\3\15\1\0\3\15\3\0\16\15\1\254\1\0\5\15"+
    "\30\0\3\15\1\0\3\15\3\0\10\15\1\255\6\15"+
    "\1\0\5\15\30\0\3\15\1\0\3\15\3\0\11\15"+
    "\1\256\5\15\1\0\5\15\30\0\3\15\1\0\3\15"+
    "\3\0\5\15\1\257\11\15\1\0\5\15\41\0\1\260"+
    "\55\0\3\15\1\0\3\15\3\0\1\15\1\261\15\15"+
    "\1\0\5\15\30\0\3\15\1\0\3\15\3\0\16\15"+
    "\1\262\1\0\5\15\30\0\3\15\1\0\3\15\3\0"+
    "\13\15\1\263\3\15\1\0\5\15\30\0\3\15\1\0"+
    "\3\15\3\0\16\15\1\264\1\0\5\15\30\0\3\15"+
    "\1\0\3\15\3\0\16\15\1\265\1\0\5\15\30\0"+
    "\3\15\1\0\3\15\3\0\12\15\1\266\4\15\1\0"+
    "\5\15\23\0\2\221\1\222\1\223\1\267\62\221\5\0"+
    "\3\15\1\0\3\15\3\0\7\15\1\270\7\15\1\0"+
    "\5\15\25\0\1\222\1\223\70\0\3\15\1\0\3\15"+
    "\3\0\1\15\1\271\15\15\1\0\5\15\23\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6490];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\7\0\1\11\2\1\1\11\27\1\2\11\6\1\12\11"+
    "\2\1\1\11\1\1\2\11\1\1\2\11\2\1\1\11"+
    "\1\1\1\11\3\1\1\11\2\1\1\11\2\0\1\1"+
    "\1\11\1\0\2\1\2\11\1\1\1\11\25\1\1\11"+
    "\1\1\6\11\1\0\1\11\1\0\1\11\1\0\2\1"+
    "\2\11\1\0\24\1\1\11\1\0\20\1\2\0\14\1"+
    "\1\0\6\1\1\0\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[185];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    ExtendedSyntaxStrCommentHandler longCommentOrStringHandler = new ExtendedSyntaxStrCommentHandler();


  _MoonLexer(java.io.Reader in) {
      this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  _MoonLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 144) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL.charAt(zzCurrentPosL++);
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL.charAt(zzCurrentPosL++);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 5: 
          { return NAME;
          }
        case 75: break;
        case 19: 
          { return LPAREN;
          }
        case 76: break;
        case 47: 
          { return GE;
          }
        case 77: break;
        case 48: 
          { yybegin( XSHORTCOMMENT ); return SHEBANG;
          }
        case 78: break;
        case 54: 
          { return AND;
          }
        case 79: break;
        case 69: 
          { return WHILE;
          }
        case 80: break;
        case 65: 
          { return LOCAL;
          }
        case 81: break;
        case 62: 
          { return TRUE;
          }
        case 82: break;
        case 28: 
          { return LONGSTRING;
          }
        case 83: break;
        case 23: 
          { return RCURLY;
          }
        case 84: break;
        case 41: 
          { yypushback(yytext().length()); yybegin( XSHORTCOMMENT ); return advance();
          }
        case 85: break;
        case 38: 
          { longCommentOrStringHandler.setCurrentExtQuoteStart(yytext().toString()); yybegin( XLONGSTRING_BEGIN ); return LONGSTRING_BEGIN;
          }
        case 86: break;
        case 72: 
          { return ELSEIF;
          }
        case 87: break;
        case 6: 
          { return NUMBER;
          }
        case 88: break;
        case 29: 
          { yypushback(1); yybegin(XLONGSTRING); return advance();
          }
        case 89: break;
        case 26: 
          { return COLON;
          }
        case 90: break;
        case 64: 
          { return BREAK;
          }
        case 91: break;
        case 73: 
          { return EXPORT;
          }
        case 92: break;
        case 40: 
          { return EQ;
          }
        case 93: break;
        case 71: 
          { return REPEAT;
          }
        case 94: break;
        case 57: 
          { return END;
          }
        case 95: break;
        case 32: 
          { yybegin(YYINITIAL); return NEWLINE;
          }
        case 96: break;
        case 22: 
          { return LCURLY;
          }
        case 97: break;
        case 13: 
          { yybegin(XSTRINGA); return STRING;
          }
        case 98: break;
        case 56: 
          { return NIL;
          }
        case 99: break;
        case 70: 
          { return RETURN;
          }
        case 100: break;
        case 2: 
          { return WS;
          }
        case 101: break;
        case 60: 
          { yypushback(1); /* TODO: Only pushback a newline */  return LUADOC_COMMENT;
          }
        case 102: break;
        case 35: 
          { yybegin(YYINITIAL); return WRONG;
          }
        case 103: break;
        case 24: 
          { return COMMA;
          }
        case 104: break;
        case 16: 
          { return MULT;
          }
        case 105: break;
        case 17: 
          { return MOD;
          }
        case 106: break;
        case 37: 
          { yybegin(YYINITIAL);return WRONG;
          }
        case 107: break;
        case 18: 
          { return DIV;
          }
        case 108: break;
        case 52: 
          { if (longCommentOrStringHandler.isCurrentExtQuoteStart(yytext())) {
                       yybegin(YYINITIAL); longCommentOrStringHandler.resetCurrentExtQuoteStart(); return LONGCOMMENT_END;
                    }  else { yypushback(yytext().length()-1); }
                  return LONGCOMMENT;
          }
        case 109: break;
        case 7: 
          { return PLUS;
          }
        case 110: break;
        case 33: 
          { return LONGCOMMENT;
          }
        case 111: break;
        case 31: 
          { return SHORTCOMMENT;
          }
        case 112: break;
        case 36: 
          { yybegin(YYINITIAL); return STRING;
          }
        case 113: break;
        case 15: 
          { return LT;
          }
        case 114: break;
        case 68: 
          { return CLASS;
          }
        case 115: break;
        case 8: 
          { return DOT;
          }
        case 116: break;
        case 43: 
          { return DO;
          }
        case 117: break;
        case 45: 
          { return IN;
          }
        case 118: break;
        case 25: 
          { return SEMI;
          }
        case 119: break;
        case 66: 
          { return FALSE;
          }
        case 120: break;
        case 11: 
          { return GT;
          }
        case 121: break;
        case 21: 
          { return RBRACK;
          }
        case 122: break;
        case 44: 
          { return OR;
          }
        case 123: break;
        case 39: 
          { return CONCAT;
          }
        case 124: break;
        case 9: 
          { return ASSIGN;
          }
        case 125: break;
        case 3: 
          { return NEWLINE;
          }
        case 126: break;
        case 4: 
          { return LBRACK;
          }
        case 127: break;
        case 53: 
          { return ELLIPSIS;
          }
        case 128: break;
        case 14: 
          { return GETN;
          }
        case 129: break;
        case 51: 
          { if (longCommentOrStringHandler.isCurrentExtQuoteStart(yytext())) {
                       yybegin(YYINITIAL); longCommentOrStringHandler.resetCurrentExtQuoteStart(); return LONGSTRING_END;
                    } else { yypushback(yytext().length()-1); }
                    return LONGSTRING;
          }
        case 130: break;
        case 42: 
          { return FUNCTION;
          }
        case 131: break;
        case 55: 
          { return NOT;
          }
        case 132: break;
        case 74: 
          { return IMPORT;
          }
        case 133: break;
        case 61: 
          { return ELSE;
          }
        case 134: break;
        case 34: 
          { return STRING;
          }
        case 135: break;
        case 46: 
          { return IF;
          }
        case 136: break;
        case 49: 
          { return NE;
          }
        case 137: break;
        case 63: 
          { return THEN;
          }
        case 138: break;
        case 67: 
          { return UNTIL;
          }
        case 139: break;
        case 10: 
          { return MINUS;
          }
        case 140: break;
        case 50: 
          { return LE;
          }
        case 141: break;
        case 58: 
          { return FOR;
          }
        case 142: break;
        case 30: 
          { return NL_BEFORE_LONGSTRING;
          }
        case 143: break;
        case 27: 
          { return EXP;
          }
        case 144: break;
        case 20: 
          { return RPAREN;
          }
        case 145: break;
        case 59: 
          { longCommentOrStringHandler.setCurrentExtQuoteStart(yytext().toString()); yybegin( XLONGCOMMENT ); return LONGCOMMENT_BEGIN;
          }
        case 146: break;
        case 1: 
          { return WRONG;
          }
        case 147: break;
        case 12: 
          { yybegin(XSTRINGQ);  return STRING;
          }
        case 148: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
