package com.eightbitmage.moonscript.options;

import com.eightbitmage.moonscript.MoonBundle;
import com.intellij.openapi.components.PersistentStateComponent;
import com.intellij.openapi.fileChooser.FileChooserDescriptor;
import com.intellij.openapi.fileChooser.FileChooserDescriptorFactory;
import com.intellij.openapi.ui.ComponentWithBrowseButton;
import com.intellij.openapi.ui.FixedSizeButton;
import com.intellij.openapi.ui.Messages;
import com.intellij.openapi.ui.TextComponentAccessor;
import com.intellij.openapi.util.text.StringUtil;
import com.intellij.ui.IdeBorderFactory;
import com.intellij.ui.StateRestoringCheckBox;
import com.intellij.ui.TextFieldWithStoredHistory;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import org.jetbrains.annotations.NonNls;
import org.jetbrains.annotations.NotNull;

import javax.swing.*;
import java.awt.*;
import java.util.Arrays;
import java.util.List;
import java.util.ResourceBundle;

/**
 * MoonScript options.
 */
public final class MoonSettingsForm implements PersistentStateComponent<MoonSettings> {
    @NonNls
    private static final String MOON_ENABLED_COMPILATION_KEY = "Moon.EnabledCompilation";
    @NonNls
    private static final String MOON_HOME_KEY = "Moon.Home";
    @NonNls
    private static final String MOON_OPTIONS_KEY = "Moon.Options";

    private ComponentWithBrowseButton<TextFieldWithStoredHistory> moonHomeTextField;
    private JPanel formComponent;
    private TextFieldWithStoredHistory commandLineOptionsTextField;
    private JCheckBox enabledCompilationCheckBox;

    private final MoonSettings settings = new MoonSettings();

    public MoonSettingsForm(MoonSettings settings) {
        $$$setupUI$$$();
        FileChooserDescriptor folderDescriptor = FileChooserDescriptorFactory.createSingleFolderDescriptor();
        FileChooserDescriptor fileDescriptor = FileChooserDescriptorFactory.createSingleLocalFileDescriptor();
        moonHomeTextField.addBrowseFolderListener(MoonBundle.message("select.moon.home"), MoonBundle.message("please.select.moon.folder"), null, folderDescriptor, new HistoryAccessor());

        loadState(settings);
    }

    private void createUIComponents() {
        enabledCompilationCheckBox = new StateRestoringCheckBox(MOON_ENABLED_COMPILATION_KEY, true);
        TextFieldWithStoredHistory moonHomeHistory = createHistoryTextField(MOON_HOME_KEY, MoonSettings.getDefaultMoonScriptHome());
        moonHomeTextField = new ComponentWithBrowseButton<TextFieldWithStoredHistory>(moonHomeHistory, null);
        fixButton(moonHomeHistory, moonHomeTextField);
         commandLineOptionsTextField = createHistoryTextField(MOON_OPTIONS_KEY, MoonSettings.DEFAULT_OPTIONS);
    }

    private void fixButton(final TextFieldWithStoredHistory historyField, ComponentWithBrowseButton<TextFieldWithStoredHistory> control) {
        FixedSizeButton button = control.getButton();
        control.remove(button);
        BorderLayout borderLayout = new BorderLayout();
        JPanel buttonPanel = new JPanel(borderLayout);
        buttonPanel.setBorder(IdeBorderFactory.createEmptyBorder(4, 0, 4, 0));
        buttonPanel.add(button, BorderLayout.CENTER);
        control.add(buttonPanel, BorderLayout.EAST);
        button.setAttachedComponent(new JComponent() {
            public Dimension getPreferredSize() {
                Dimension size = historyField.getTextEditor().getPreferredSize();
                return new Dimension(-1, size.height + 6);
            }

        });
    }

    @SuppressWarnings({"unchecked"})
    private static TextFieldWithStoredHistory createHistoryTextField(@NotNull String name, @NotNull String... defaultValues) {
        TextFieldWithStoredHistory storedHistory = new TextFieldWithStoredHistoryBugFixed(name);
        storedHistory.reset();
        List<String> list = storedHistory.getHistory();
        list.removeAll(Arrays.asList(defaultValues));
        if (list.isEmpty()) {
            // Default histories
            for (String defaultValue : defaultValues) {
                setTextWithHistory(storedHistory, defaultValue);
            }
        } else {
            storedHistory.setSelectedItem(list.get(list.size() - 1));
        }
        return storedHistory;
    }

    public JComponent getFormComponent() {
        return formComponent;
    }

    public boolean isModified(MoonSettings state) {
        return enabledCompilationCheckBox.isSelected() != state.ENABLED_COMPILATION ||
            !moonHomeTextField.getChildComponent().getText().equals(state.MOON_HOME) ||
            !commandLineOptionsTextField.getText().equals(state.COMMAND_LINE_OPTIONS);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        formComponent = new JPanel();
        formComponent.setLayout(new GridLayoutManager(5, 2, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        this.$$$loadLabelText$$$(label1, ResourceBundle.getBundle("org/intellij/lang/jflex/util/JFlexBundle").getString("path.to.jflex"));
        formComponent.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        formComponent.add(spacer1, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        formComponent.add(moonHomeTextField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        this.$$$loadLabelText$$$(label2, ResourceBundle.getBundle("org/intellij/lang/jflex/util/JFlexBundle").getString("skeleton.file"));
        formComponent.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        this.$$$loadLabelText$$$(label3, ResourceBundle.getBundle("org/intellij/lang/jflex/util/JFlexBundle").getString("command.line.options"));
        formComponent.add(label3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        formComponent.add(commandLineOptionsTextField, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        label1.setLabelFor(moonHomeTextField);
         label3.setLabelFor(commandLineOptionsTextField);
    }

    /**
     * @noinspection ALL
     */
    private void $$$loadLabelText$$$(JLabel component, String text) {
        StringBuffer result = new StringBuffer();
        boolean haveMnemonic = false;
        char mnemonic = '\0';
        int mnemonicIndex = -1;
        for (int i = 0; i < text.length(); i++) {
            if (text.charAt(i) == '&') {
                i++;
                if (i == text.length()) {
                    break;
                }
                if (!haveMnemonic && text.charAt(i) != '&') {
                    haveMnemonic = true;
                    mnemonic = text.charAt(i);
                    mnemonicIndex = result.length();
                }
            }
            result.append(text.charAt(i));
        }
        component.setText(result.toString());
        if (haveMnemonic) {
            component.setDisplayedMnemonic(mnemonic);
            component.setDisplayedMnemonicIndex(mnemonicIndex);
        }
    }

    /**
     * @noinspection ALL
     */
    private void $$$loadButtonText$$$(AbstractButton component, String text) {
        StringBuffer result = new StringBuffer();
        boolean haveMnemonic = false;
        char mnemonic = '\0';
        int mnemonicIndex = -1;
        for (int i = 0; i < text.length(); i++) {
            if (text.charAt(i) == '&') {
                i++;
                if (i == text.length()) {
                    break;
                }
                if (!haveMnemonic && text.charAt(i) != '&') {
                    haveMnemonic = true;
                    mnemonic = text.charAt(i);
                    mnemonicIndex = result.length();
                }
            }
            result.append(text.charAt(i));
        }
        component.setText(result.toString());
        if (haveMnemonic) {
            component.setMnemonic(mnemonic);
            component.setDisplayedMnemonicIndex(mnemonicIndex);
        }
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return formComponent;
    }


    /**
     * Fixed text component. Enabling is valid now.
     */
    private static final class TextFieldWithStoredHistoryBugFixed extends TextFieldWithStoredHistory {
        public TextFieldWithStoredHistoryBugFixed(String name) {
            super(name, false);
        }

        public void setEnabled(boolean enabled) {
            super.setEnabled(enabled);
            getTextEditor().setEnabled(enabled);
            getTextEditor().setEditable(enabled);
        }
    }

    private static class HistoryAccessor implements TextComponentAccessor<TextFieldWithStoredHistory> {
        public String getText(TextFieldWithStoredHistory component) {
            return component.getText().replace('\\', '/');
        }

        public void setText(TextFieldWithStoredHistory component, String text) {
            setTextWithHistory(component, text);
        }
    }

    public final MoonSettings getState() {
        if (validate()) {
            settings.ENABLED_COMPILATION = enabledCompilationCheckBox.isSelected();
            settings.MOON_HOME = moonHomeTextField.getChildComponent().getText();
            settings.COMMAND_LINE_OPTIONS = commandLineOptionsTextField.getText();
        }
        return settings;
    }

    private boolean validate() {
        if (enabledCompilationCheckBox.isSelected()) {
            String text = moonHomeTextField.getChildComponent().getText();
            if (StringUtil.isEmptyOrSpaces(text)) {
                Messages.showWarningDialog(moonHomeTextField, MoonBundle.message("please.enter.path.to.jflex.home.directory"), MoonBundle.message("moon"));
                moonHomeTextField.requestFocus();
                return false;
            }

            // All fine add to history
            moonHomeTextField.getChildComponent().addCurrentTextToHistory();
            commandLineOptionsTextField.addCurrentTextToHistory();
        }
        return true;
    }

    public final void loadState(MoonSettings state) {
        settings.loadState(state);
        enabledCompilationCheckBox.setSelected(state.ENABLED_COMPILATION);
        setTextWithHistory(moonHomeTextField.getChildComponent(), state.MOON_HOME);
        setTextWithHistory(commandLineOptionsTextField, state.COMMAND_LINE_OPTIONS);
    }

    private static void setTextWithHistory(TextFieldWithStoredHistory component, String text) {
        if (StringUtil.isEmptyOrSpaces(text)) {
            component.setText(null);
        } else {
            component.setText(text);
            component.addCurrentTextToHistory();
        }
    }

}
